### ISSUE TITLE
How to use VARIABLES for body content?

### ISSUE THREAD

**Issue by drkNsubuga** [jaywcjlove/github-action-modify-file-content#8]
Hello, I tried using a variable set in  in a body section but it was returned as is.
``` yaml
-name: Set Description
SECTION_DETAILS="This is a test content"
- name: Update README section
   uses: jaywcjlove/github-action-modify-file-content@v1.4.3
      with:
        path: README.md
        body: "$SECTION_DETAILS"
        openDelimiter: "<!-- start-section -->"
        closeDelimiter: "<!-- end-section -->" 
```
